version: "3.5"
services:
  rsyslog:
    image: vmware/harbor-log:v1.5.2
    volumes:
      # - "./rsyslog.conf:/etc/rsyslog.conf"
      # - "./rsyslog.d:/etc/rsyslog.d"
      - "./logrotate.d:/etc/logrotate.d"
      # - "./rsyslog:/var/spool/rsyslog"
      - "./log/:/var/log/docker/:z"
    ports:
      - "127.0.0.1:514:10514"
      - "127.0.0.1:514:10514/udp"
    networks:
      - rsyslog-network
  nginx:
    image: nginx:alpine
    depends_on:
      - rsyslog
    ports:
      - "80:80"
    networks:
      - rsyslog-network
    logging:
      driver: "syslog"
      options:  
        syslog-address: "udp://127.0.0.1:514"
        tag: "nginx"
  httpd:
    image: httpd:alpine
    depends_on:
      - rsyslog
    ports:
      - "8080:80"
    networks:
      - rsyslog-network
    logging:
      driver: "syslog"
      options:  
        syslog-address: "udp://127.0.0.1:514"
        tag: "httpd"
networks:
  rsyslog-network:
    name: rsyslog-network
    driver: bridge